p01:
	python3 ws.bitio.read.part.1.py
	python3 ws.bitio.read.part.2.py
	python3 ws.bitio.write.part.1.py
	python3 ws.bitio.write.part.2.py
	python3 ws.bitio.write.part.3.py

qs:
	time python3 quicksort.large.py

clean:
	-/bin/rm -r -f __pycache__
	rm output.?
