# Week 4
slide:
	python3 slide08.py
	python3 slide08v2.py

l6:
	python3 lec06.p01.py
	python3 lec06.p02.py

l7:
	python3 lec07.p01.py < num.1
	python3 lec07.p02.py
	cat output.1

clean:
	-rm output.1
