# Week 3
lec05:
	cat count.the.p4.v1.lec05.p03.py
	python3 count.the.p4.v1.lec05.p03.py < paul.words.2
	-cp count.the.p4.v1.lec05.p03.py countp4.py
	python3 driver.v01.count.the.p4.v1.lec05.p03.py < paul.words.2
	python3 driver.v02.count.the.p4.v1.lec05.p03.py < paul.words.2
	python3 driver.v03.count.the.p4.v1.lec05.p03.py < paul.words.2

p2:
	python3 lec04.p02.py

p1:
	python3 lec04.p01.py

style:
	python3 ../Style/stylecheck.py lec04.p01.py
	python3 ../Style/stylecheck.py lec04.p02.py

clean:
	-rm countp4.py
